name: Sync opera/utils to (greasemonkey|chrome|edge)/utils && adamlui/python-utils

on:
  push:
    branches: [ master, main ]
    paths: 'opera/utils/translate-en-messages.py'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/python-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/python-utils
          path: adamlui/python-utils          

      - name: Sync opera/utils/translate-en-messages.py to (greasemonkey|chrome|edge)/utils/translate-en-messages.py
        run: |
          for platform in greasemonkey chrome edge
          do
            cp -f -v "${{ github.workspace }}/adamlui/chatgpt-widescreen/opera/utils/translate-en-messages.py" "${{ github.workspace }}/adamlui/chatgpt-widescreen/$platform/utils/translate-en-messages.py"
          done

      - name: Sync opera/utils/translate-en-messages.py to adamlui/python-utils/translate-messages/translate-en-messages.py
        run: cp -f -v ${{ github.workspace }}/adamlui/chatgpt-widescreen/opera/utils/translate-en-messages.py ${{ github.workspace }}/adamlui/python-utils/translate-messages/translate-en-messages.py

      - name: Push to adamlui/python-utils
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} â†ž [auto-sync from `adamlui/chatgpt-widescreen`]'
          file_pattern: '**/translate-en-messages.py'
          repository: adamlui/python-utils
