name: Sync /* to adamlui/chatgpt-addons/chatgpt-widescreen/*

on:
  push:
    branches: [ master, main ]
    paths:
      - '/*'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/chatgpt-addons
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-addons
          path: adamlui/chatgpt-addons

      - name: Sync /* to adamlui/chatgpt-addons/chatgpt-widescreen/*
        run: rsync -avh --delete --exclude={'.git','.github'} ${{ github.workspace }}/adamlui/chatgpt-widescreen/ ${{ github.workspace }}/adamlui/chatgpt-addons/chatgpt-widescreen/

      - name: Push to adamlui/chatgpt-addons
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@chatgptevo.com
          commit_message: '${{ github.event.head_commit.message }} â†ž [auto-sync from `adamlui/chatgpt-widescreen`]'
          file_pattern: 'chatgpt-widescreen/*'
          repository: adamlui/chatgpt-addons
